### ISSUE TITLE
Forge 32.0.97 - Fatal error Method public void

### ISSUE THREAD

**Issue by WHCTHBD** [mactso/HappyTrails#1]
```
[10:21:23] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: ht, class com.mactso.HT.Main
java.lang.IllegalArgumentException: Method public void com.mactso.HT.Main.onServerStarting(net.minecraftforge.fml.event.server.FMLServerStartingEvent) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.fml.event.server.FMLServerStartingEvent
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:145) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$null$6(EventBus.java:98) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3058/59748199.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:98) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$3055/751787179.accept(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-3.0.3-service.jar:?]
	at com.mactso.HT.Main.<init>(Main.java:25) ~[?:1.0.0.3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:136) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2948/2063059370.accept(Unknown Source) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) [?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) [?:?]
	at net.minecraftforge.fml.ModList.lambda$null$11(ModList.java:135) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$3036/1293854735.accept(Unknown Source) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) [?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_51]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[10:21:23] [modloading-worker-0/ERROR]: An error occurred while dispatching event CONSTRUCT to ht
```

**Comment by mactso** [comment]
Thanks, looking into this.

Forge changed the way /commands worked  around 32.0.90.

You'll need to use an older forge or get a newer version Happy Trails written to comply with the new requirements.   We have a newer version on curseforge that should work tho I haven't tested with 32.0.97 specifically.

Please try the most current version out and reopen the issue if it's still occurring.  I'll be running and testing everything with most current forge this weekend.
